/* Generated by Yosys 0.16+65 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* top =  1  *)
module ff(d, clk, q);
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  reg q;
  always @(posedge clk)
    q <= d;
endmodule
