/* Generated by Yosys 0.16+65 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* top =  1  *)
module add4(a, b, o);
  (* packed_ranges = 1'h1 *)
  (* unpacked_ranges = 1'h1 *)
  input [3:0] a;
  wire [3:0] a;
  (* packed_ranges = 1'h1 *)
  (* unpacked_ranges = 1'h1 *)
  input [3:0] b;
  wire [3:0] b;
  (* packed_ranges = 1'h1 *)
  (* unpacked_ranges = 1'h1 *)
  output [3:0] o;
  wire [3:0] o;
  assign o = a + b;
endmodule
