/* Generated by Yosys 0.16+65 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* top =  1  *)
module seven_segment(segment, data);
  (* packed_ranges = 1'h1 *)
  (* unpacked_ranges = 1'h1 *)
  input [3:0] data;
  wire [3:0] data;
  wire outA1;
  wire outA2;
  wire outA3;
  wire outA4;
  wire outB1;
  wire outB2;
  wire outB3;
  wire outB4;
  wire outB5;
  wire outB6;
  wire outC1;
  wire outC2;
  wire outC3;
  (* packed_ranges = 1'h1 *)
  (* unpacked_ranges = 1'h1 *)
  output [6:0] segment;
  wire [6:0] segment;
  assign { 6'h00, data[0] } = 7'h00 | 1'h0;
  assign { 6'h00, data[0] } = 7'h00 | data[0];
  assign outA1 = 1'h0;
  assign outA2 = 1'h0;
  assign outA3 = 1'h0;
  assign outA4 = 1'h0;
  assign outB1 = 1'h0;
  assign outB2 = 1'h0;
  assign outB3 = 1'h0;
  assign outB4 = 1'h0;
  assign outB5 = 1'h0;
  assign outB6 = data[0];
  assign outC1 = 1'h0;
  assign outC2 = 1'h0;
  assign outC3 = data[0];
  assign segment = { 6'h00, data[0] };
endmodule
