/* Generated by Yosys 0.16+65 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* top =  1  *)
module add8_r_rst(a, b, clk, rst, o);
  wire [7:0] _0_;
  (* packed_ranges = 1'h1 *)
  (* unpacked_ranges = 1'h1 *)
  input [7:0] a;
  wire [7:0] a;
  (* packed_ranges = 1'h1 *)
  (* unpacked_ranges = 1'h1 *)
  input [7:0] b;
  wire [7:0] b;
  input clk;
  wire clk;
  (* packed_ranges = 1'h1 *)
  (* unpacked_ranges = 1'h1 *)
  output [7:0] o;
  reg [7:0] o;
  input rst;
  wire rst;
  assign _0_ = a + b;
  always @(posedge clk)
    if (rst) o <= 8'h00;
    else o <= _0_;
endmodule
