/* Generated by Yosys 0.16+65 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* top =  1  *)
module and3_r(a, b, c, clk, o);
  wire _0_;
  wire _1_;
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  input clk;
  wire clk;
  output o;
  reg o;
  assign _1_ = a & b;
  assign _0_ = _1_ & c;
  always @(posedge clk)
    o <= _0_;
endmodule
